import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <script dangerouslySetInnerHTML={{ __html: `https://telegram.org/js/telegram-web-app.js` }} />
            </Head>
            <body className={inter.className}>{children}</body>
        </html>
    )
}
