import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Script src="https://telegram.org/js/telegram-web-app.js" strategy='beforeInteractive'/>
                {children}
            </body>
        </html>
    )
}
